const schoolHistoryData = [{"name":"Lowe-Collier","duration":"2024-2024","grade":"K8","conduct_grade":"Y","is_active":true},
{"name":"Bartell Group","duration":"2027-2022","grade":"K8","conduct_grade":"L","is_active":false},
{"name":"Bartell-Morissette","duration":"2021-2021","grade":"K4","conduct_grade":"A","is_active":true},
{"name":"Reilly Group","duration":"2028-2029","grade":"K4","conduct_grade":"N","is_active":false},
{"name":"Orn, Schroeder and Brekke","duration":"2026-2028","grade":"K5","conduct_grade":"R","is_active":false},
{"name":"Botsford Inc","duration":"2026-2029","grade":"K4","conduct_grade":"I","is_active":false},
{"name":"Gusikowski, Casper and Schuster","duration":"2021-2026","grade":"K6","conduct_grade":"X","is_active":false},
{"name":"Effertz-Pollich","duration":"2026-2022","grade":"K3","conduct_grade":"P","is_active":true},
{"name":"Bartell, Lindgren and Schaefer","duration":"2026-2022","grade":"K9","conduct_grade":"P","is_active":false},
{"name":"Cole and Sons","duration":"2024-2025","grade":"K8","conduct_grade":"I","is_active":true},
{"name":"Altenwerth and Sons","duration":"2028-2023","grade":"K2","conduct_grade":"B","is_active":false},
{"name":"Kovacek, Padberg and Vandervort","duration":"2023-2027","grade":"K8","conduct_grade":"F","is_active":true},
{"name":"Bayer Group","duration":"2025-2020","grade":"K3","conduct_grade":"R","is_active":false},
{"name":"Klein-McLaughlin","duration":"2025-2021","grade":"K3","conduct_grade":"X","is_active":false},
{"name":"Friesen, Fay and Altenwerth","duration":"2022-2028","grade":"K9","conduct_grade":"Q","is_active":true},
{"name":"Padberg-Schimmel","duration":"2028-2029","grade":"K1","conduct_grade":"R","is_active":false},
{"name":"Batz and Sons","duration":"2022-2024","grade":"K3","conduct_grade":"A","is_active":true},
{"name":"Nicolas and Sons","duration":"2024-2021","grade":"K3","conduct_grade":"T","is_active":false},
{"name":"Bednar Inc","duration":"2027-2020","grade":"K9","conduct_grade":"S","is_active":true},
{"name":"Bednar, Johnson and Reichel","duration":"2029-2029","grade":"K5","conduct_grade":"A","is_active":false},
{"name":"Paucek Inc","duration":"2023-2025","grade":"K5","conduct_grade":"T","is_active":true},
{"name":"Volkman Group","duration":"2029-2026","grade":"K0","conduct_grade":"X","is_active":true},
{"name":"Batz LLC","duration":"2026-2020","grade":"K8","conduct_grade":"G","is_active":true},
{"name":"Gutmann LLC","duration":"2027-2025","grade":"K9","conduct_grade":"M","is_active":true},
{"name":"Schinner LLC","duration":"2027-2020","grade":"K8","conduct_grade":"X","is_active":true},
{"name":"Emard, Towne and Weimann","duration":"2027-2022","grade":"K7","conduct_grade":"C","is_active":true},
{"name":"Marks, Morar and Wolf","duration":"2024-2023","grade":"K0","conduct_grade":"V","is_active":true},
{"name":"Doyle and Sons","duration":"2028-2022","grade":"K2","conduct_grade":"P","is_active":false},
{"name":"Moore LLC","duration":"2027-2024","grade":"K8","conduct_grade":"O","is_active":true},
{"name":"Upton Group","duration":"2027-2025","grade":"K2","conduct_grade":"P","is_active":true},
{"name":"Welch, Feeney and Glover","duration":"2020-2024","grade":"K8","conduct_grade":"X","is_active":false},
{"name":"Denesik-Harber","duration":"2021-2021","grade":"K3","conduct_grade":"B","is_active":false},
{"name":"Rau-Harris","duration":"2022-2028","grade":"K4","conduct_grade":"Q","is_active":true},
{"name":"Abbott Group","duration":"2020-2021","grade":"K5","conduct_grade":"U","is_active":false},
{"name":"Grimes, Kohler and Davis","duration":"2025-2022","grade":"K8","conduct_grade":"Y","is_active":false},
{"name":"White-Wilkinson","duration":"2023-2022","grade":"K2","conduct_grade":"Q","is_active":true},
{"name":"Trantow and Sons","duration":"2021-2028","grade":"K0","conduct_grade":"S","is_active":true},
{"name":"Gaylord-Bogan","duration":"2020-2029","grade":"K2","conduct_grade":"D","is_active":false},
{"name":"Mitchell-Schuster","duration":"2023-2021","grade":"K2","conduct_grade":"Q","is_active":false},
{"name":"Jaskolski Inc","duration":"2027-2028","grade":"K3","conduct_grade":"S","is_active":true},
{"name":"Altenwerth LLC","duration":"2028-2020","grade":"K1","conduct_grade":"L","is_active":true},
{"name":"Wilderman-Abernathy","duration":"2022-2028","grade":"K6","conduct_grade":"Z","is_active":false},
{"name":"Nikolaus Group","duration":"2021-2024","grade":"K3","conduct_grade":"N","is_active":true},
{"name":"Schuppe-Pouros","duration":"2021-2025","grade":"K4","conduct_grade":"U","is_active":false},
{"name":"Halvorson, Metz and Schultz","duration":"2027-2024","grade":"K6","conduct_grade":"X","is_active":false},
{"name":"Reichel Inc","duration":"2026-2021","grade":"K0","conduct_grade":"I","is_active":true},
{"name":"Bahringer, Homenick and Marks","duration":"2026-2022","grade":"K5","conduct_grade":"E","is_active":false},
{"name":"Romaguera Group","duration":"2028-2023","grade":"K6","conduct_grade":"A","is_active":true},
{"name":"Kling Inc","duration":"2024-2026","grade":"K8","conduct_grade":"T","is_active":true},
{"name":"O'Hara Inc","duration":"2024-2022","grade":"K5","conduct_grade":"H","is_active":true},
{"name":"Leuschke, Marquardt and Brown","duration":"2026-2021","grade":"K1","conduct_grade":"S","is_active":true},
{"name":"Lang, Vandervort and Parisian","duration":"2023-2029","grade":"K1","conduct_grade":"G","is_active":true},
{"name":"Kuhlman, Halvorson and Maggio","duration":"2029-2026","grade":"K9","conduct_grade":"K","is_active":false},
{"name":"Green, Marvin and Cormier","duration":"2028-2029","grade":"K0","conduct_grade":"K","is_active":false},
{"name":"Lockman, Davis and Stiedemann","duration":"2021-2026","grade":"K7","conduct_grade":"Y","is_active":false},
{"name":"Davis LLC","duration":"2025-2027","grade":"K9","conduct_grade":"O","is_active":true},
{"name":"Nader, Osinski and Hilll","duration":"2022-2026","grade":"K3","conduct_grade":"D","is_active":false},
{"name":"Botsford, Dickinson and Corwin","duration":"2022-2024","grade":"K3","conduct_grade":"C","is_active":false},
{"name":"Runolfsdottir LLC","duration":"2023-2020","grade":"K7","conduct_grade":"Y","is_active":false},
{"name":"Spinka, Farrell and Pfeffer","duration":"2029-2029","grade":"K2","conduct_grade":"Q","is_active":true},
{"name":"Kunze, O'Hara and Feil","duration":"2020-2025","grade":"K9","conduct_grade":"R","is_active":false},
{"name":"Rempel, Towne and Cummerata","duration":"2022-2022","grade":"K7","conduct_grade":"B","is_active":true},
{"name":"Weimann, Hand and Volkman","duration":"2029-2023","grade":"K2","conduct_grade":"B","is_active":true},
{"name":"Jacobson and Sons","duration":"2025-2028","grade":"K8","conduct_grade":"G","is_active":false},
{"name":"Larson, Swaniawski and Gerhold","duration":"2027-2027","grade":"K8","conduct_grade":"U","is_active":false},
{"name":"King-MacGyver","duration":"2026-2021","grade":"K2","conduct_grade":"K","is_active":false},
{"name":"Macejkovic-Hilpert","duration":"2027-2024","grade":"K9","conduct_grade":"Q","is_active":false},
{"name":"Weimann-Koepp","duration":"2022-2029","grade":"K3","conduct_grade":"A","is_active":false},
{"name":"Harber-Parker","duration":"2023-2022","grade":"K7","conduct_grade":"R","is_active":false},
{"name":"Jacobs-Veum","duration":"2025-2022","grade":"K8","conduct_grade":"M","is_active":false},
{"name":"Waelchi and Sons","duration":"2028-2027","grade":"K9","conduct_grade":"N","is_active":true},
{"name":"Blick Group","duration":"2025-2021","grade":"K8","conduct_grade":"Q","is_active":true},
{"name":"Ferry-McGlynn","duration":"2023-2022","grade":"K7","conduct_grade":"L","is_active":true},
{"name":"Gutkowski Group","duration":"2020-2023","grade":"K4","conduct_grade":"G","is_active":false},
{"name":"Blanda Group","duration":"2026-2026","grade":"K4","conduct_grade":"R","is_active":false},
{"name":"Douglas Inc","duration":"2021-2028","grade":"K3","conduct_grade":"K","is_active":false},
{"name":"Dicki Inc","duration":"2020-2022","grade":"K7","conduct_grade":"W","is_active":false},
{"name":"Hills-Bruen","duration":"2026-2026","grade":"K9","conduct_grade":"C","is_active":false},
{"name":"McLaughlin LLC","duration":"2028-2020","grade":"K0","conduct_grade":"U","is_active":false},
{"name":"Kohler, Jakubowski and Friesen","duration":"2028-2020","grade":"K4","conduct_grade":"C","is_active":true},
{"name":"Olson LLC","duration":"2026-2025","grade":"K5","conduct_grade":"A","is_active":false},
{"name":"Nolan-Marquardt","duration":"2021-2026","grade":"K7","conduct_grade":"J","is_active":false},
{"name":"Senger-Feil","duration":"2028-2026","grade":"K8","conduct_grade":"V","is_active":true},
{"name":"D'Amore-Hessel","duration":"2021-2029","grade":"K2","conduct_grade":"A","is_active":true},
{"name":"Doyle, Schaden and Halvorson","duration":"2026-2027","grade":"K8","conduct_grade":"M","is_active":false},
{"name":"Howe LLC","duration":"2029-2023","grade":"K8","conduct_grade":"D","is_active":true},
{"name":"Krajcik-Bergstrom","duration":"2021-2025","grade":"K0","conduct_grade":"Q","is_active":false},
{"name":"Altenwerth, Hartmann and Lemke","duration":"2020-2021","grade":"K9","conduct_grade":"S","is_active":true},
{"name":"Corwin and Sons","duration":"2027-2026","grade":"K7","conduct_grade":"T","is_active":true},
{"name":"Halvorson and Sons","duration":"2025-2029","grade":"K1","conduct_grade":"D","is_active":false},
{"name":"Stanton LLC","duration":"2025-2022","grade":"K4","conduct_grade":"B","is_active":false},
{"name":"Schoen, Hagenes and Hartmann","duration":"2025-2028","grade":"K9","conduct_grade":"H","is_active":false},
{"name":"Adams Inc","duration":"2024-2025","grade":"K8","conduct_grade":"D","is_active":false},
{"name":"Hammes Group","duration":"2027-2027","grade":"K7","conduct_grade":"T","is_active":false},
{"name":"West, Nicolas and Block","duration":"2024-2028","grade":"K7","conduct_grade":"R","is_active":true},
{"name":"Adams, Leannon and Kerluke","duration":"2029-2021","grade":"K7","conduct_grade":"C","is_active":false},
{"name":"O'Reilly, Will and Ratke","duration":"2027-2020","grade":"K0","conduct_grade":"F","is_active":true},
{"name":"Casper Inc","duration":"2027-2026","grade":"K5","conduct_grade":"J","is_active":true},
{"name":"King, Emmerich and Connelly","duration":"2023-2029","grade":"K7","conduct_grade":"U","is_active":true},
{"name":"King-Jenkins","duration":"2027-2024","grade":"K7","conduct_grade":"T","is_active":false},
{"name":"Morar, O'Hara and Rutherford","duration":"2024-2029","grade":"K6","conduct_grade":"M","is_active":false},
{"name":"Howell-Witting","duration":"2023-2025","grade":"K1","conduct_grade":"F","is_active":true},
{"name":"Hirthe and Sons","duration":"2027-2027","grade":"K9","conduct_grade":"I","is_active":false},
{"name":"Dickens and Sons","duration":"2026-2027","grade":"K1","conduct_grade":"Z","is_active":false},
{"name":"Berge, Dickinson and Murray","duration":"2026-2026","grade":"K1","conduct_grade":"G","is_active":true},
{"name":"Veum Inc","duration":"2027-2025","grade":"K4","conduct_grade":"B","is_active":false},
{"name":"Schiller-Hodkiewicz","duration":"2021-2020","grade":"K2","conduct_grade":"C","is_active":true},
{"name":"Stiedemann-Tillman","duration":"2024-2025","grade":"K2","conduct_grade":"X","is_active":true},
{"name":"Lebsack, Abshire and Raynor","duration":"2024-2024","grade":"K8","conduct_grade":"X","is_active":true},
{"name":"Pfeffer Group","duration":"2020-2028","grade":"K0","conduct_grade":"B","is_active":false},
{"name":"Ritchie, Abshire and Swift","duration":"2029-2023","grade":"K3","conduct_grade":"N","is_active":true},
{"name":"Brekke, Sanford and Ullrich","duration":"2023-2026","grade":"K3","conduct_grade":"E","is_active":true},
{"name":"Treutel-Runolfsdottir","duration":"2020-2027","grade":"K4","conduct_grade":"G","is_active":false},
{"name":"Hudson, Conn and Sawayn","duration":"2029-2028","grade":"K3","conduct_grade":"W","is_active":true},
{"name":"Dare-Brown","duration":"2023-2022","grade":"K4","conduct_grade":"M","is_active":true},
{"name":"Nader, Rath and Gusikowski","duration":"2027-2029","grade":"K2","conduct_grade":"L","is_active":true},
{"name":"Feest-Stokes","duration":"2027-2028","grade":"K0","conduct_grade":"U","is_active":false},
{"name":"Schumm-Keeling","duration":"2029-2024","grade":"K9","conduct_grade":"G","is_active":true},
{"name":"Howell-Miller","duration":"2026-2029","grade":"K2","conduct_grade":"I","is_active":false},
{"name":"Tromp, Kshlerin and Zboncak","duration":"2025-2026","grade":"K0","conduct_grade":"Q","is_active":true},
{"name":"Moen, Moore and Nolan","duration":"2023-2025","grade":"K9","conduct_grade":"I","is_active":false},
{"name":"Jast-Buckridge","duration":"2028-2027","grade":"K1","conduct_grade":"M","is_active":false},
{"name":"Brekke, Daniel and Schiller","duration":"2029-2020","grade":"K5","conduct_grade":"B","is_active":true},
{"name":"Auer Inc","duration":"2024-2022","grade":"K4","conduct_grade":"C","is_active":false},
{"name":"Gleichner, Brown and Walker","duration":"2026-2025","grade":"K9","conduct_grade":"M","is_active":true},
{"name":"Denesik, Breitenberg and Rath","duration":"2025-2020","grade":"K4","conduct_grade":"K","is_active":true},
{"name":"D'Amore and Sons","duration":"2026-2021","grade":"K1","conduct_grade":"D","is_active":true},
{"name":"Connelly, Muller and Hahn","duration":"2022-2021","grade":"K2","conduct_grade":"O","is_active":true},
{"name":"Medhurst, Barton and Stokes","duration":"2027-2026","grade":"K7","conduct_grade":"R","is_active":true},
{"name":"Hahn-Paucek","duration":"2021-2021","grade":"K5","conduct_grade":"U","is_active":true},
{"name":"Kris-Tromp","duration":"2025-2022","grade":"K0","conduct_grade":"A","is_active":true},
{"name":"Simonis Inc","duration":"2023-2020","grade":"K3","conduct_grade":"V","is_active":true},
{"name":"Fritsch-O'Reilly","duration":"2020-2024","grade":"K8","conduct_grade":"I","is_active":false},
{"name":"Smith, Ortiz and Goyette","duration":"2029-2027","grade":"K0","conduct_grade":"K","is_active":true},
{"name":"Kautzer and Sons","duration":"2026-2020","grade":"K5","conduct_grade":"S","is_active":false},
{"name":"Metz, Turcotte and McClure","duration":"2022-2023","grade":"K7","conduct_grade":"D","is_active":false},
{"name":"Strosin, Kihn and Schneider","duration":"2027-2020","grade":"K5","conduct_grade":"T","is_active":false},
{"name":"Hayes, Cole and Waelchi","duration":"2027-2020","grade":"K3","conduct_grade":"L","is_active":false},
{"name":"Jenkins-Robel","duration":"2028-2020","grade":"K5","conduct_grade":"U","is_active":false},
{"name":"Corwin-Beier","duration":"2029-2025","grade":"K3","conduct_grade":"X","is_active":false},
{"name":"Thiel-Wehner","duration":"2028-2024","grade":"K2","conduct_grade":"J","is_active":true},
{"name":"Rempel Group","duration":"2026-2026","grade":"K5","conduct_grade":"T","is_active":false},
{"name":"Beer-Kilback","duration":"2023-2028","grade":"K9","conduct_grade":"N","is_active":true},
{"name":"Ryan, Carter and Cruickshank","duration":"2028-2024","grade":"K4","conduct_grade":"P","is_active":false},
{"name":"Marquardt-Block","duration":"2025-2025","grade":"K4","conduct_grade":"G","is_active":false},
{"name":"Ziemann-Boyle","duration":"2024-2021","grade":"K5","conduct_grade":"L","is_active":true},
{"name":"Franecki, Prosacco and Krajcik","duration":"2026-2025","grade":"K8","conduct_grade":"E","is_active":true},
{"name":"Schaefer, Hudson and Batz","duration":"2022-2028","grade":"K3","conduct_grade":"P","is_active":false},
{"name":"Goldner, Bins and Nader","duration":"2020-2026","grade":"K3","conduct_grade":"X","is_active":false},
{"name":"Lockman and Sons","duration":"2021-2028","grade":"K8","conduct_grade":"R","is_active":false},
{"name":"Schaden-Smith","duration":"2028-2029","grade":"K9","conduct_grade":"R","is_active":true},
{"name":"Brown LLC","duration":"2025-2023","grade":"K1","conduct_grade":"A","is_active":false},
{"name":"Crist and Sons","duration":"2025-2028","grade":"K2","conduct_grade":"B","is_active":false},
{"name":"Emard, Skiles and Dicki","duration":"2027-2021","grade":"K2","conduct_grade":"B","is_active":false},
{"name":"Strosin and Sons","duration":"2024-2026","grade":"K2","conduct_grade":"L","is_active":false},
{"name":"Ortiz, Rohan and Powlowski","duration":"2022-2021","grade":"K8","conduct_grade":"Z","is_active":true},
{"name":"Murazik-Bauch","duration":"2029-2025","grade":"K8","conduct_grade":"I","is_active":true},
{"name":"Macejkovic LLC","duration":"2021-2028","grade":"K8","conduct_grade":"I","is_active":true},
{"name":"Sawayn Inc","duration":"2029-2024","grade":"K8","conduct_grade":"J","is_active":false},
{"name":"Littel-Rosenbaum","duration":"2027-2020","grade":"K0","conduct_grade":"B","is_active":false},
{"name":"Ward-Ondricka","duration":"2026-2025","grade":"K7","conduct_grade":"T","is_active":false},
{"name":"Moen-Friesen","duration":"2027-2021","grade":"K8","conduct_grade":"U","is_active":false},
{"name":"Larson Group","duration":"2027-2028","grade":"K9","conduct_grade":"X","is_active":true},
{"name":"MacGyver and Sons","duration":"2023-2028","grade":"K2","conduct_grade":"I","is_active":true},
{"name":"Jacobs-Smith","duration":"2027-2022","grade":"K6","conduct_grade":"R","is_active":true},
{"name":"O'Hara-Hayes","duration":"2020-2028","grade":"K1","conduct_grade":"Q","is_active":false},
{"name":"Lesch, Douglas and Crona","duration":"2025-2029","grade":"K6","conduct_grade":"J","is_active":true},
{"name":"Ryan-Nicolas","duration":"2026-2026","grade":"K3","conduct_grade":"A","is_active":false},
{"name":"Walter, Rowe and Block","duration":"2026-2022","grade":"K8","conduct_grade":"H","is_active":true},
{"name":"Nolan, MacGyver and Jerde","duration":"2027-2023","grade":"K1","conduct_grade":"A","is_active":true},
{"name":"Kunde LLC","duration":"2023-2028","grade":"K3","conduct_grade":"H","is_active":true},
{"name":"Botsford-Moen","duration":"2023-2024","grade":"K9","conduct_grade":"X","is_active":false},
{"name":"Kemmer Group","duration":"2027-2020","grade":"K2","conduct_grade":"L","is_active":false},
{"name":"Nienow-Ledner","duration":"2021-2023","grade":"K5","conduct_grade":"E","is_active":false},
{"name":"Schroeder LLC","duration":"2028-2027","grade":"K0","conduct_grade":"A","is_active":true},
{"name":"Hermann, Bayer and Daniel","duration":"2027-2024","grade":"K6","conduct_grade":"T","is_active":true},
{"name":"Murazik LLC","duration":"2029-2026","grade":"K9","conduct_grade":"V","is_active":true},
{"name":"Kovacek LLC","duration":"2022-2026","grade":"K9","conduct_grade":"R","is_active":true},
{"name":"Hickle Group","duration":"2020-2021","grade":"K7","conduct_grade":"K","is_active":true},
{"name":"Bosco and Sons","duration":"2025-2020","grade":"K7","conduct_grade":"V","is_active":false},
{"name":"Kertzmann Inc","duration":"2020-2027","grade":"K1","conduct_grade":"Y","is_active":false},
{"name":"Olson, DuBuque and Murazik","duration":"2026-2027","grade":"K3","conduct_grade":"Q","is_active":false},
{"name":"McCullough-Gorczany","duration":"2023-2027","grade":"K1","conduct_grade":"N","is_active":false},
{"name":"Ferry and Sons","duration":"2023-2022","grade":"K1","conduct_grade":"F","is_active":false},
{"name":"Hackett, Deckow and McLaughlin","duration":"2028-2020","grade":"K9","conduct_grade":"I","is_active":true},
{"name":"Lindgren and Sons","duration":"2025-2023","grade":"K3","conduct_grade":"B","is_active":false},
{"name":"Welch, Labadie and Fisher","duration":"2024-2020","grade":"K0","conduct_grade":"P","is_active":false},
{"name":"Cruickshank, Sanford and Breitenberg","duration":"2022-2021","grade":"K3","conduct_grade":"U","is_active":false},
{"name":"Runolfsson Inc","duration":"2029-2020","grade":"K5","conduct_grade":"H","is_active":true},
{"name":"Strosin-Hammes","duration":"2025-2029","grade":"K3","conduct_grade":"H","is_active":false},
{"name":"Marks Group","duration":"2023-2023","grade":"K7","conduct_grade":"H","is_active":true},
{"name":"Gulgowski Inc","duration":"2021-2026","grade":"K8","conduct_grade":"P","is_active":false},
{"name":"Schmidt, Schaden and Murazik","duration":"2028-2022","grade":"K4","conduct_grade":"K","is_active":false},
{"name":"Rempel, Lemke and Hane","duration":"2026-2025","grade":"K9","conduct_grade":"G","is_active":false},
{"name":"Beatty, Paucek and Mraz","duration":"2021-2020","grade":"K2","conduct_grade":"I","is_active":false},
{"name":"Kuvalis and Sons","duration":"2024-2022","grade":"K1","conduct_grade":"D","is_active":false},
{"name":"Crist-Hand","duration":"2026-2024","grade":"K8","conduct_grade":"O","is_active":true},
{"name":"Runolfsson and Sons","duration":"2024-2022","grade":"K1","conduct_grade":"Z","is_active":false},
{"name":"Emmerich-Hickle","duration":"2022-2020","grade":"K9","conduct_grade":"T","is_active":true},
{"name":"Douglas-Medhurst","duration":"2022-2026","grade":"K3","conduct_grade":"G","is_active":false},
{"name":"Tillman-Rolfson","duration":"2022-2028","grade":"K7","conduct_grade":"C","is_active":true},
{"name":"Hessel-Baumbach","duration":"2028-2027","grade":"K8","conduct_grade":"W","is_active":true},
{"name":"Glover Group","duration":"2023-2022","grade":"K4","conduct_grade":"R","is_active":false},
{"name":"Lang Group","duration":"2021-2024","grade":"K7","conduct_grade":"F","is_active":false},
{"name":"White and Sons","duration":"2023-2027","grade":"K7","conduct_grade":"B","is_active":false},
{"name":"Grady, McKenzie and Tromp","duration":"2022-2027","grade":"K8","conduct_grade":"G","is_active":false},
{"name":"Lowe, Langworth and Hodkiewicz","duration":"2022-2020","grade":"K6","conduct_grade":"Q","is_active":false},
{"name":"Ferry LLC","duration":"2020-2028","grade":"K7","conduct_grade":"P","is_active":false},
{"name":"Pfeffer-Kuvalis","duration":"2021-2023","grade":"K3","conduct_grade":"H","is_active":false},
{"name":"Nicolas LLC","duration":"2022-2020","grade":"K6","conduct_grade":"G","is_active":true},
{"name":"Bartell Group","duration":"2025-2027","grade":"K3","conduct_grade":"Z","is_active":false},
{"name":"Rau, Franecki and Leuschke","duration":"2027-2023","grade":"K4","conduct_grade":"S","is_active":false},
{"name":"Prosacco, Heidenreich and Kertzmann","duration":"2021-2024","grade":"K9","conduct_grade":"S","is_active":true},
{"name":"Von-Carter","duration":"2028-2024","grade":"K2","conduct_grade":"J","is_active":false},
{"name":"Gerhold LLC","duration":"2028-2026","grade":"K9","conduct_grade":"E","is_active":true},
{"name":"Roberts-Smitham","duration":"2026-2027","grade":"K2","conduct_grade":"W","is_active":false},
{"name":"Windler-Haag","duration":"2029-2027","grade":"K9","conduct_grade":"N","is_active":true},
{"name":"Weber, Ondricka and Hackett","duration":"2020-2025","grade":"K5","conduct_grade":"X","is_active":true},
{"name":"Hansen LLC","duration":"2026-2021","grade":"K2","conduct_grade":"R","is_active":true},
{"name":"Stehr and Sons","duration":"2028-2027","grade":"K2","conduct_grade":"L","is_active":true},
{"name":"Connelly-Rau","duration":"2023-2028","grade":"K0","conduct_grade":"J","is_active":true},
{"name":"Gutmann-Goyette","duration":"2022-2028","grade":"K4","conduct_grade":"O","is_active":false},
{"name":"Conroy-Dicki","duration":"2024-2020","grade":"K5","conduct_grade":"N","is_active":true},
{"name":"Brakus Group","duration":"2020-2021","grade":"K2","conduct_grade":"S","is_active":false},
{"name":"Harris, Lang and Marquardt","duration":"2021-2024","grade":"K7","conduct_grade":"S","is_active":true},
{"name":"Pfannerstill-Boyer","duration":"2028-2020","grade":"K5","conduct_grade":"F","is_active":false},
{"name":"Grimes and Sons","duration":"2024-2024","grade":"K2","conduct_grade":"Z","is_active":false},
{"name":"Bechtelar Inc","duration":"2023-2027","grade":"K7","conduct_grade":"L","is_active":true},
{"name":"Herzog and Sons","duration":"2021-2022","grade":"K5","conduct_grade":"N","is_active":true},
{"name":"Wolff-Dibbert","duration":"2029-2020","grade":"K4","conduct_grade":"F","is_active":true},
{"name":"Feest, Mertz and Kuhic","duration":"2026-2021","grade":"K1","conduct_grade":"N","is_active":false},
{"name":"Parisian, Becker and Deckow","duration":"2023-2025","grade":"K4","conduct_grade":"G","is_active":true},
{"name":"Altenwerth and Sons","duration":"2020-2023","grade":"K6","conduct_grade":"J","is_active":true},
{"name":"Collier, Schumm and Gleichner","duration":"2023-2020","grade":"K6","conduct_grade":"C","is_active":true},
{"name":"Hackett Group","duration":"2026-2026","grade":"K2","conduct_grade":"T","is_active":true},
{"name":"Keeling-Carroll","duration":"2029-2023","grade":"K0","conduct_grade":"F","is_active":true},
{"name":"Padberg and Sons","duration":"2026-2026","grade":"K1","conduct_grade":"X","is_active":false},
{"name":"Jacobs LLC","duration":"2028-2027","grade":"K6","conduct_grade":"Q","is_active":true},
{"name":"Gerhold, Borer and Berge","duration":"2025-2025","grade":"K4","conduct_grade":"E","is_active":true},
{"name":"Monahan LLC","duration":"2021-2021","grade":"K4","conduct_grade":"T","is_active":true},
{"name":"Sawayn-Batz","duration":"2024-2023","grade":"K1","conduct_grade":"R","is_active":true},
{"name":"Skiles-Wilderman","duration":"2023-2023","grade":"K6","conduct_grade":"K","is_active":true},
{"name":"Padberg, Kulas and Bruen","duration":"2029-2022","grade":"K2","conduct_grade":"F","is_active":true},
{"name":"Hane Inc","duration":"2025-2029","grade":"K9","conduct_grade":"C","is_active":true},
{"name":"Johnston, Yundt and Considine","duration":"2025-2025","grade":"K7","conduct_grade":"H","is_active":false},
{"name":"Aufderhar-Rowe","duration":"2023-2025","grade":"K8","conduct_grade":"F","is_active":false},
{"name":"Daugherty Inc","duration":"2021-2025","grade":"K4","conduct_grade":"O","is_active":false},
{"name":"Doyle, Crona and Wolf","duration":"2021-2023","grade":"K9","conduct_grade":"R","is_active":false},
{"name":"Bednar, Beier and Effertz","duration":"2028-2029","grade":"K1","conduct_grade":"R","is_active":false},
{"name":"Kling and Sons","duration":"2027-2027","grade":"K8","conduct_grade":"G","is_active":true},
{"name":"Zemlak-Botsford","duration":"2025-2026","grade":"K3","conduct_grade":"B","is_active":false},
{"name":"Reichert-McGlynn","duration":"2020-2026","grade":"K2","conduct_grade":"Z","is_active":false},
{"name":"Hamill Group","duration":"2020-2025","grade":"K7","conduct_grade":"O","is_active":false},
{"name":"Medhurst, Mraz and Bernhard","duration":"2025-2026","grade":"K8","conduct_grade":"Z","is_active":false},
{"name":"Beer, Corkery and Blick","duration":"2022-2020","grade":"K0","conduct_grade":"U","is_active":true},
{"name":"Wilkinson, Krajcik and Hintz","duration":"2023-2025","grade":"K8","conduct_grade":"W","is_active":true},
{"name":"Mitchell-Keeling","duration":"2027-2020","grade":"K4","conduct_grade":"D","is_active":true},
{"name":"Kreiger, Robel and Bahringer","duration":"2022-2027","grade":"K7","conduct_grade":"T","is_active":true},
{"name":"Bernhard, Dickens and Kuphal","duration":"2027-2024","grade":"K3","conduct_grade":"Z","is_active":false},
{"name":"Batz and Sons","duration":"2021-2024","grade":"K9","conduct_grade":"D","is_active":false},
{"name":"Bogan-Hills","duration":"2026-2024","grade":"K0","conduct_grade":"S","is_active":false},
{"name":"Witting Group","duration":"2027-2020","grade":"K4","conduct_grade":"R","is_active":true},
{"name":"Eichmann, Hudson and Jaskolski","duration":"2022-2024","grade":"K0","conduct_grade":"X","is_active":true},
{"name":"Krajcik-Bernier","duration":"2020-2024","grade":"K3","conduct_grade":"Q","is_active":true},
{"name":"Parker-Franecki","duration":"2025-2028","grade":"K8","conduct_grade":"B","is_active":true},
{"name":"Kuphal, Collins and Shanahan","duration":"2029-2021","grade":"K8","conduct_grade":"E","is_active":false},
{"name":"Osinski Group","duration":"2025-2024","grade":"K4","conduct_grade":"C","is_active":false},
{"name":"Veum and Sons","duration":"2022-2021","grade":"K9","conduct_grade":"Y","is_active":false},
{"name":"Gleichner, Donnelly and Paucek","duration":"2025-2021","grade":"K6","conduct_grade":"F","is_active":false},
{"name":"McClure-Lueilwitz","duration":"2021-2027","grade":"K5","conduct_grade":"Q","is_active":true},
{"name":"Kuhic-Rogahn","duration":"2022-2026","grade":"K1","conduct_grade":"C","is_active":false},
{"name":"Wolf LLC","duration":"2021-2027","grade":"K7","conduct_grade":"T","is_active":false},
{"name":"Marvin, Flatley and Erdman","duration":"2028-2022","grade":"K9","conduct_grade":"R","is_active":true},
{"name":"Ullrich-Muller","duration":"2023-2024","grade":"K7","conduct_grade":"J","is_active":true},
{"name":"Turcotte-Leannon","duration":"2020-2024","grade":"K6","conduct_grade":"C","is_active":true},
{"name":"Renner LLC","duration":"2022-2028","grade":"K2","conduct_grade":"T","is_active":true},
{"name":"Kris-Smith","duration":"2026-2029","grade":"K1","conduct_grade":"C","is_active":true},
{"name":"Konopelski Inc","duration":"2027-2024","grade":"K2","conduct_grade":"G","is_active":true},
{"name":"Jones-Walter","duration":"2029-2029","grade":"K9","conduct_grade":"X","is_active":true},
{"name":"Howe and Sons","duration":"2029-2029","grade":"K0","conduct_grade":"T","is_active":false},
{"name":"Murazik, Schuppe and Barrows","duration":"2021-2028","grade":"K4","conduct_grade":"L","is_active":false},
{"name":"Prohaska-Graham","duration":"2023-2026","grade":"K0","conduct_grade":"N","is_active":false},
{"name":"Weimann-Jones","duration":"2027-2024","grade":"K6","conduct_grade":"X","is_active":true},
{"name":"Schaden-MacGyver","duration":"2027-2028","grade":"K3","conduct_grade":"R","is_active":false},
{"name":"Sawayn LLC","duration":"2022-2022","grade":"K8","conduct_grade":"F","is_active":false},
{"name":"Stamm, Hettinger and Flatley","duration":"2029-2022","grade":"K9","conduct_grade":"G","is_active":false},
{"name":"Schneider Inc","duration":"2025-2023","grade":"K4","conduct_grade":"I","is_active":true},
{"name":"Weissnat and Sons","duration":"2021-2029","grade":"K5","conduct_grade":"W","is_active":false},
{"name":"Stoltenberg Group","duration":"2028-2024","grade":"K8","conduct_grade":"I","is_active":false},
{"name":"Towne-Connelly","duration":"2026-2027","grade":"K7","conduct_grade":"M","is_active":true},
{"name":"Beahan LLC","duration":"2026-2029","grade":"K5","conduct_grade":"K","is_active":false},
{"name":"Halvorson-Hackett","duration":"2025-2024","grade":"K4","conduct_grade":"K","is_active":true},
{"name":"Predovic, Bogan and Bosco","duration":"2025-2021","grade":"K0","conduct_grade":"T","is_active":true},
{"name":"Bogan-Bergstrom","duration":"2024-2024","grade":"K2","conduct_grade":"R","is_active":true},
{"name":"Dickens-Jaskolski","duration":"2021-2025","grade":"K8","conduct_grade":"M","is_active":true},
{"name":"Schumm, Stroman and Armstrong","duration":"2023-2029","grade":"K3","conduct_grade":"V","is_active":false},
{"name":"Beer Group","duration":"2026-2029","grade":"K4","conduct_grade":"V","is_active":false},
{"name":"Koss, Ritchie and Hettinger","duration":"2029-2028","grade":"K4","conduct_grade":"Z","is_active":false},
{"name":"Paucek-Monahan","duration":"2028-2020","grade":"K2","conduct_grade":"K","is_active":false},
{"name":"Wunsch, Dickinson and Botsford","duration":"2025-2020","grade":"K5","conduct_grade":"V","is_active":true}]

export default schoolHistoryData;