const siblingData = [{"name":"Ian Viste","school_name":"hardware","is_active":false,"sex":"Female"},
{"name":"Luise Derobert","school_name":"Proactive","is_active":true,"sex":"Female"},
{"name":"Eduino Jackson","school_name":"client-driven","is_active":true,"sex":"Female"},
{"name":"Jacki Kunze","school_name":"grid-enabled","is_active":true,"sex":"Male"},
{"name":"Javier Algar","school_name":"Synergized","is_active":false,"sex":"Female"},
{"name":"Erminie De Lacey","school_name":"Configurable","is_active":false,"sex":"Female"},
{"name":"Bridgette Croll","school_name":"algorithm","is_active":false,"sex":"Female"},
{"name":"Mahmoud Fortune","school_name":"Configurable","is_active":false,"sex":"Female"},
{"name":"Mala Keaves","school_name":"website","is_active":true,"sex":"Female"},
{"name":"Field Tutt","school_name":"well-modulated","is_active":true,"sex":"Male"},
{"name":"Merla Snellman","school_name":"responsive","is_active":true,"sex":"Male"},
{"name":"Riki Kubica","school_name":"productivity","is_active":false,"sex":"Female"},
{"name":"Ruthi Thunderchief","school_name":"challenge","is_active":true,"sex":"Male"},
{"name":"Gabrielle Batrick","school_name":"scalable","is_active":true,"sex":"Male"},
{"name":"Roseline Croix","school_name":"local area network","is_active":false,"sex":"Female"},
{"name":"Renaldo Hissie","school_name":"open system","is_active":false,"sex":"Male"},
{"name":"Kippy Seebright","school_name":"Switchable","is_active":true,"sex":"Female"},
{"name":"Bertram Schaumann","school_name":"application","is_active":true,"sex":"Female"},
{"name":"August Vint","school_name":"Open-architected","is_active":false,"sex":"Female"},
{"name":"Esta Ashfield","school_name":"capability","is_active":true,"sex":"Male"},
{"name":"Mattie Jeays","school_name":"Open-source","is_active":true,"sex":"Female"},
{"name":"Thomasine Spriggs","school_name":"paradigm","is_active":false,"sex":"Female"},
{"name":"Victoria Schaben","school_name":"bandwidth-monitored","is_active":false,"sex":"Male"},
{"name":"Romola Faldo","school_name":"Seamless","is_active":false,"sex":"Male"},
{"name":"Carley Chettle","school_name":"local","is_active":false,"sex":"Male"},
{"name":"Elyn Punchard","school_name":"systematic","is_active":false,"sex":"Female"},
{"name":"Rhys Mannie","school_name":"reciprocal","is_active":true,"sex":"Female"},
{"name":"Morley Reeks","school_name":"object-oriented","is_active":false,"sex":"Male"},
{"name":"Dorey Megainey","school_name":"artificial intelligence","is_active":true,"sex":"Male"},
{"name":"Meagan Pindell","school_name":"Up-sized","is_active":true,"sex":"Female"},
{"name":"Noelyn Wanne","school_name":"bifurcated","is_active":false,"sex":"Female"},
{"name":"Hobie Laminman","school_name":"Re-contextualized","is_active":false,"sex":"Male"},
{"name":"Lewes Klossmann","school_name":"time-frame","is_active":true,"sex":"Male"},
{"name":"Tonye Skipper","school_name":"parallelism","is_active":false,"sex":"Female"},
{"name":"Mic Weiss","school_name":"zero defect","is_active":true,"sex":"Female"},
{"name":"Suzy Jakubovitch","school_name":"non-volatile","is_active":true,"sex":"Male"},
{"name":"Torrance Poletto","school_name":"high-level","is_active":true,"sex":"Male"},
{"name":"Abramo Pretti","school_name":"circuit","is_active":true,"sex":"Male"},
{"name":"Nehemiah Damper","school_name":"Ergonomic","is_active":false,"sex":"Male"},
{"name":"Brade Purslow","school_name":"complexity","is_active":false,"sex":"Male"},
{"name":"Gordon Robertz","school_name":"attitude","is_active":true,"sex":"Female"},
{"name":"Brigitta Caistor","school_name":"attitude","is_active":false,"sex":"Male"},
{"name":"Elwyn Storek","school_name":"encompassing","is_active":false,"sex":"Female"},
{"name":"Peadar Schulter","school_name":"logistical","is_active":false,"sex":"Female"},
{"name":"Shem Bonus","school_name":"Managed","is_active":false,"sex":"Female"},
{"name":"Verine Hulcoop","school_name":"Synergistic","is_active":true,"sex":"Female"},
{"name":"Billye Farrear","school_name":"Team-oriented","is_active":false,"sex":"Female"},
{"name":"Cesar Yurikov","school_name":"attitude-oriented","is_active":true,"sex":"Female"},
{"name":"Leslie Rosenwasser","school_name":"directional","is_active":false,"sex":"Male"},
{"name":"Dalila Van Baaren","school_name":"workforce","is_active":true,"sex":"Female"},
{"name":"Anestassia Matonin","school_name":"implementation","is_active":true,"sex":"Female"},
{"name":"Fremont Garrals","school_name":"6th generation","is_active":false,"sex":"Female"},
{"name":"Savina Leethem","school_name":"bi-directional","is_active":false,"sex":"Female"},
{"name":"Tuesday Davidsohn","school_name":"Public-key","is_active":true,"sex":"Male"},
{"name":"Donny Simak","school_name":"internet solution","is_active":true,"sex":"Female"},
{"name":"Irma Stoaks","school_name":"Devolved","is_active":true,"sex":"Female"},
{"name":"Ogdan De La Haye","school_name":"framework","is_active":true,"sex":"Male"},
{"name":"Dick Murie","school_name":"Graphical User Interface","is_active":true,"sex":"Male"},
{"name":"Feliks Hanwell","school_name":"composite","is_active":true,"sex":"Female"},
{"name":"Lorilyn Sharpless","school_name":"Cloned","is_active":true,"sex":"Male"},
{"name":"Georas Davison","school_name":"secondary","is_active":true,"sex":"Male"},
{"name":"Sergei Gascoigne","school_name":"5th generation","is_active":true,"sex":"Male"},
{"name":"Luciano Dimitriades","school_name":"analyzing","is_active":false,"sex":"Female"},
{"name":"Humfried Leber","school_name":"website","is_active":true,"sex":"Male"},
{"name":"Lorenza Barends","school_name":"monitoring","is_active":true,"sex":"Female"},
{"name":"Arturo Poulsen","school_name":"throughput","is_active":true,"sex":"Female"},
{"name":"Gaylor Klassmann","school_name":"zero tolerance","is_active":false,"sex":"Male"},
{"name":"Drusy Mollett","school_name":"interface","is_active":true,"sex":"Male"},
{"name":"Elsinore Maly","school_name":"Profound","is_active":false,"sex":"Male"},
{"name":"Fidela Rainard","school_name":"workforce","is_active":true,"sex":"Female"},
{"name":"Brigid Statham","school_name":"website","is_active":false,"sex":"Female"},
{"name":"Shayne Breeton","school_name":"time-frame","is_active":true,"sex":"Female"},
{"name":"Annabella Soares","school_name":"context-sensitive","is_active":false,"sex":"Male"},
{"name":"Griff Lindop","school_name":"Self-enabling","is_active":true,"sex":"Female"},
{"name":"Granville Gobeau","school_name":"Exclusive","is_active":false,"sex":"Male"},
{"name":"Petey Inglis","school_name":"Function-based","is_active":true,"sex":"Male"},
{"name":"Wayland Badland","school_name":"Diverse","is_active":true,"sex":"Male"},
{"name":"Erl Setford","school_name":"Enterprise-wide","is_active":true,"sex":"Male"},
{"name":"Meredithe Bachs","school_name":"moratorium","is_active":true,"sex":"Male"},
{"name":"Aldon Padson","school_name":"Synchronised","is_active":false,"sex":"Male"},
{"name":"Pepi Eadmead","school_name":"methodical","is_active":true,"sex":"Female"},
{"name":"Harriet Folling","school_name":"forecast","is_active":false,"sex":"Male"},
{"name":"Theo Nelius","school_name":"Team-oriented","is_active":false,"sex":"Female"},
{"name":"Johny Vasilmanov","school_name":"time-frame","is_active":true,"sex":"Male"},
{"name":"Timi Crosetto","school_name":"interactive","is_active":true,"sex":"Female"},
{"name":"Eugene Garatty","school_name":"24/7","is_active":true,"sex":"Male"},
{"name":"Biddy Gounard","school_name":"encompassing","is_active":true,"sex":"Male"},
{"name":"Gaylord Hummerston","school_name":"24 hour","is_active":true,"sex":"Male"},
{"name":"Myranda Larkby","school_name":"optimal","is_active":false,"sex":"Male"},
{"name":"Tish Petrina","school_name":"uniform","is_active":true,"sex":"Male"},
{"name":"Don Boole","school_name":"moderator","is_active":true,"sex":"Male"},
{"name":"Blanca Middlemist","school_name":"intermediate","is_active":false,"sex":"Female"},
{"name":"Pauline Sides","school_name":"focus group","is_active":false,"sex":"Female"},
{"name":"Blakelee Ayton","school_name":"data-warehouse","is_active":false,"sex":"Male"},
{"name":"Selie Verry","school_name":"Graphic Interface","is_active":false,"sex":"Male"},
{"name":"Ringo Rogers","school_name":"help-desk","is_active":true,"sex":"Female"},
{"name":"Saba Fallon","school_name":"Universal","is_active":true,"sex":"Male"},
{"name":"Jereme Szepe","school_name":"fault-tolerant","is_active":true,"sex":"Female"},
{"name":"Chad Marrion","school_name":"product","is_active":false,"sex":"Female"},
{"name":"Pepito Wherry","school_name":"methodology","is_active":false,"sex":"Male"},
{"name":"Ronald Mottram","school_name":"alliance","is_active":false,"sex":"Female"},
{"name":"Raquela Kryszka","school_name":"multimedia","is_active":true,"sex":"Female"},
{"name":"Margaret Sked","school_name":"Devolved","is_active":true,"sex":"Male"},
{"name":"Louella Morfell","school_name":"ability","is_active":true,"sex":"Male"},
{"name":"Eunice Creane","school_name":"human-resource","is_active":false,"sex":"Male"},
{"name":"Kayley Gallienne","school_name":"solution","is_active":false,"sex":"Female"},
{"name":"Andreas Pottes","school_name":"Proactive","is_active":false,"sex":"Female"},
{"name":"Renell Rolfi","school_name":"Face to face","is_active":true,"sex":"Female"},
{"name":"Fowler Siddons","school_name":"Upgradable","is_active":true,"sex":"Female"},
{"name":"Gradeigh MacCallester","school_name":"Fully-configurable","is_active":false,"sex":"Female"},
{"name":"Aggi Sealove","school_name":"firmware","is_active":true,"sex":"Male"},
{"name":"Milissent Teale","school_name":"initiative","is_active":true,"sex":"Male"},
{"name":"Jillian Blackstone","school_name":"Multi-tiered","is_active":true,"sex":"Female"},
{"name":"Ermin Evamy","school_name":"Function-based","is_active":true,"sex":"Male"},
{"name":"Sigismundo Lightbown","school_name":"knowledge user","is_active":false,"sex":"Female"},
{"name":"Iris Baptiste","school_name":"Open-architected","is_active":true,"sex":"Female"},
{"name":"Elinor Thornebarrow","school_name":"exuding","is_active":true,"sex":"Female"},
{"name":"Papagena Hovy","school_name":"Customer-focused","is_active":true,"sex":"Male"},
{"name":"Kari Ludwell","school_name":"data-warehouse","is_active":true,"sex":"Female"},
{"name":"Mariana Videan","school_name":"archive","is_active":false,"sex":"Female"},
{"name":"Augie Breadon","school_name":"Open-architected","is_active":false,"sex":"Male"},
{"name":"Nelie Hacket","school_name":"asynchronous","is_active":false,"sex":"Female"},
{"name":"Yvon Astill","school_name":"knowledge base","is_active":true,"sex":"Male"},
{"name":"Ring Baxendale","school_name":"hardware","is_active":false,"sex":"Male"},
{"name":"Muffin Verchambre","school_name":"dynamic","is_active":false,"sex":"Female"},
{"name":"Bonnee Shorte","school_name":"transitional","is_active":true,"sex":"Female"},
{"name":"Lorrie Culmer","school_name":"3rd generation","is_active":false,"sex":"Female"},
{"name":"Merna Domanek","school_name":"hardware","is_active":true,"sex":"Female"},
{"name":"Gib Ronayne","school_name":"Upgradable","is_active":true,"sex":"Male"},
{"name":"Buddie Ridgley","school_name":"Multi-tiered","is_active":false,"sex":"Male"},
{"name":"Angele Gorey","school_name":"function","is_active":true,"sex":"Male"},
{"name":"Antonius Selvey","school_name":"methodology","is_active":true,"sex":"Male"},
{"name":"Kellyann Milleton","school_name":"Intuitive","is_active":false,"sex":"Male"},
{"name":"Stanislas McMeekan","school_name":"local area network","is_active":true,"sex":"Male"},
{"name":"Normy Guerra","school_name":"contextually-based","is_active":false,"sex":"Male"},
{"name":"Nada Akett","school_name":"Graphic Interface","is_active":true,"sex":"Male"},
{"name":"Rhody Juris","school_name":"Cloned","is_active":true,"sex":"Female"},
{"name":"Cornell Cherrison","school_name":"Upgradable","is_active":false,"sex":"Male"},
{"name":"Kirbie Whoston","school_name":"instruction set","is_active":true,"sex":"Male"},
{"name":"Eileen Steutly","school_name":"Streamlined","is_active":true,"sex":"Male"},
{"name":"Carmencita Winridge","school_name":"utilisation","is_active":false,"sex":"Male"},
{"name":"Benedetto Snalom","school_name":"methodical","is_active":true,"sex":"Male"},
{"name":"Tamera Balam","school_name":"Synchronised","is_active":true,"sex":"Female"},
{"name":"Bernelle Avrahamoff","school_name":"discrete","is_active":true,"sex":"Female"},
{"name":"Thoma Bardey","school_name":"Exclusive","is_active":false,"sex":"Female"},
{"name":"Marillin Le Lievre","school_name":"Compatible","is_active":false,"sex":"Female"},
{"name":"Hatti Banville","school_name":"Integrated","is_active":true,"sex":"Female"},
{"name":"Kip Sanchez","school_name":"Expanded","is_active":true,"sex":"Male"},
{"name":"Brig Mitchell","school_name":"infrastructure","is_active":true,"sex":"Male"},
{"name":"Rand Blagburn","school_name":"radical","is_active":false,"sex":"Male"},
{"name":"Kellyann Cottey","school_name":"homogeneous","is_active":true,"sex":"Male"},
{"name":"Aurilia Leftbridge","school_name":"holistic","is_active":true,"sex":"Male"},
{"name":"Elayne Blakeslee","school_name":"analyzing","is_active":false,"sex":"Female"},
{"name":"Job Klazenga","school_name":"Ameliorated","is_active":true,"sex":"Female"},
{"name":"Gretal Pilmoor","school_name":"workforce","is_active":false,"sex":"Female"},
{"name":"Richart Skelding","school_name":"artificial intelligence","is_active":false,"sex":"Male"},
{"name":"Kele Slyne","school_name":"Ameliorated","is_active":true,"sex":"Female"},
{"name":"Fidelity Paslow","school_name":"neutral","is_active":false,"sex":"Male"},
{"name":"Mariellen Bobasch","school_name":"Automated","is_active":false,"sex":"Male"},
{"name":"Aviva Friedenbach","school_name":"customer loyalty","is_active":false,"sex":"Female"},
{"name":"Lorrie Kik","school_name":"Down-sized","is_active":false,"sex":"Female"},
{"name":"Winni Domonkos","school_name":"bandwidth-monitored","is_active":false,"sex":"Male"},
{"name":"Merrill Labro","school_name":"Robust","is_active":false,"sex":"Female"},
{"name":"Adlai Revill","school_name":"data-warehouse","is_active":true,"sex":"Male"},
{"name":"Gilberte Cousans","school_name":"core","is_active":false,"sex":"Male"},
{"name":"Anna-diana Mattiato","school_name":"circuit","is_active":true,"sex":"Female"},
{"name":"Elyssa Muldownie","school_name":"background","is_active":false,"sex":"Male"},
{"name":"Mignonne Mewrcik","school_name":"heuristic","is_active":false,"sex":"Female"},
{"name":"Ceciley Weddell","school_name":"holistic","is_active":false,"sex":"Male"},
{"name":"Darill Buzine","school_name":"Reverse-engineered","is_active":true,"sex":"Female"},
{"name":"Katrina Henzer","school_name":"transitional","is_active":true,"sex":"Female"},
{"name":"Nomi Officer","school_name":"benchmark","is_active":true,"sex":"Male"},
{"name":"Chic Greatorex","school_name":"multi-state","is_active":false,"sex":"Female"},
{"name":"Gaylene Hurdis","school_name":"open architecture","is_active":false,"sex":"Female"},
{"name":"Helena Clem","school_name":"needs-based","is_active":true,"sex":"Female"},
{"name":"Morgan Shawcroft","school_name":"radical","is_active":false,"sex":"Male"},
{"name":"Keary Gibard","school_name":"success","is_active":false,"sex":"Male"},
{"name":"Gabrila Newick","school_name":"high-level","is_active":true,"sex":"Male"},
{"name":"Lynn Carren","school_name":"function","is_active":true,"sex":"Male"},
{"name":"Norry Ivkovic","school_name":"middleware","is_active":false,"sex":"Female"},
{"name":"Paulie Tomblin","school_name":"application","is_active":false,"sex":"Female"},
{"name":"Wilmer McNuff","school_name":"real-time","is_active":false,"sex":"Male"},
{"name":"Mycah Simmance","school_name":"alliance","is_active":true,"sex":"Male"},
{"name":"Debee Lampert","school_name":"Advanced","is_active":false,"sex":"Male"},
{"name":"Ferne Lighton","school_name":"regional","is_active":true,"sex":"Male"},
{"name":"Edwin Jagielski","school_name":"intermediate","is_active":true,"sex":"Male"},
{"name":"Ginger Grzelczyk","school_name":"dynamic","is_active":true,"sex":"Male"},
{"name":"Philippe Camellini","school_name":"Persevering","is_active":false,"sex":"Male"},
{"name":"Rosemaria Pozer","school_name":"Organic","is_active":true,"sex":"Female"},
{"name":"Kiri Shreve","school_name":"holistic","is_active":true,"sex":"Male"},
{"name":"Cherry Dunwoody","school_name":"Right-sized","is_active":true,"sex":"Female"},
{"name":"Worthington Langrick","school_name":"tangible","is_active":false,"sex":"Male"},
{"name":"Daffi Bennett","school_name":"emulation","is_active":false,"sex":"Female"},
{"name":"Tommy Kordas","school_name":"optimal","is_active":true,"sex":"Male"},
{"name":"Sile Adess","school_name":"emulation","is_active":true,"sex":"Male"},
{"name":"Jethro Sperling","school_name":"Streamlined","is_active":false,"sex":"Male"},
{"name":"Rutledge Sidnall","school_name":"protocol","is_active":true,"sex":"Male"},
{"name":"Benedikt Hindmore","school_name":"intranet","is_active":true,"sex":"Male"},
{"name":"Maryann Merill","school_name":"human-resource","is_active":true,"sex":"Female"},
{"name":"Vally Cottem","school_name":"paradigm","is_active":true,"sex":"Male"},
{"name":"Griselda Clissell","school_name":"Multi-tiered","is_active":true,"sex":"Female"},
{"name":"Otis Eynaud","school_name":"hybrid","is_active":true,"sex":"Male"},
{"name":"Fons Nutbeem","school_name":"Managed","is_active":true,"sex":"Female"},
{"name":"Richy Summerson","school_name":"methodology","is_active":true,"sex":"Male"},
{"name":"Addy Le Maitre","school_name":"dynamic","is_active":false,"sex":"Female"},
{"name":"Alonso Coxen","school_name":"solution-oriented","is_active":true,"sex":"Female"},
{"name":"Asher Varran","school_name":"Focused","is_active":false,"sex":"Female"},
{"name":"Cozmo Izod","school_name":"impactful","is_active":true,"sex":"Male"},
{"name":"Huntley Yeaman","school_name":"Innovative","is_active":false,"sex":"Male"},
{"name":"Alexei Faber","school_name":"Integrated","is_active":true,"sex":"Male"},
{"name":"Lynsey Pallent","school_name":"utilisation","is_active":true,"sex":"Female"},
{"name":"Hortensia Pengelley","school_name":"alliance","is_active":false,"sex":"Male"},
{"name":"Johnette Coomes","school_name":"Fundamental","is_active":false,"sex":"Male"},
{"name":"Josselyn Gerauld","school_name":"solution","is_active":true,"sex":"Female"},
{"name":"Zia Alloisi","school_name":"fault-tolerant","is_active":true,"sex":"Female"},
{"name":"Sebastiano Gwin","school_name":"Programmable","is_active":true,"sex":"Male"},
{"name":"Wylma Rossborough","school_name":"zero defect","is_active":false,"sex":"Female"},
{"name":"Flor Weatherhill","school_name":"hub","is_active":true,"sex":"Male"},
{"name":"Richmond Brixham","school_name":"Organized","is_active":true,"sex":"Female"},
{"name":"Conrad Langelaan","school_name":"User-centric","is_active":true,"sex":"Female"},
{"name":"Melodie Summerly","school_name":"disintermediate","is_active":true,"sex":"Male"},
{"name":"Ramon Sutehall","school_name":"Decentralized","is_active":false,"sex":"Male"},
{"name":"Bentley Biss","school_name":"encoding","is_active":false,"sex":"Female"},
{"name":"Berta Fogt","school_name":"dedicated","is_active":false,"sex":"Male"},
{"name":"Phillip Eddins","school_name":"intangible","is_active":false,"sex":"Female"},
{"name":"Dara Rait","school_name":"maximized","is_active":true,"sex":"Female"},
{"name":"Bent Brainsby","school_name":"mobile","is_active":false,"sex":"Female"},
{"name":"Raynor Senussi","school_name":"Right-sized","is_active":false,"sex":"Female"},
{"name":"Abbi Tomowicz","school_name":"encryption","is_active":false,"sex":"Male"},
{"name":"Ali Herion","school_name":"installation","is_active":false,"sex":"Male"},
{"name":"Nanine Torritti","school_name":"software","is_active":true,"sex":"Male"},
{"name":"Kary Castanares","school_name":"motivating","is_active":false,"sex":"Male"},
{"name":"Stern Heijnen","school_name":"stable","is_active":false,"sex":"Female"},
{"name":"Merrily Bensley","school_name":"standardization","is_active":false,"sex":"Male"},
{"name":"Lowell Whimp","school_name":"grid-enabled","is_active":false,"sex":"Male"},
{"name":"Lemar Reay","school_name":"Down-sized","is_active":true,"sex":"Female"},
{"name":"Sharleen Leer","school_name":"portal","is_active":false,"sex":"Male"},
{"name":"Nicolais Markwick","school_name":"Persistent","is_active":false,"sex":"Female"},
{"name":"Christan Bindin","school_name":"Ameliorated","is_active":true,"sex":"Female"},
{"name":"Kimble Draysay","school_name":"installation","is_active":true,"sex":"Female"},
{"name":"Baldwin Hurle","school_name":"matrix","is_active":true,"sex":"Male"},
{"name":"Bettine Govey","school_name":"strategy","is_active":false,"sex":"Male"},
{"name":"Idalia Burkett","school_name":"Networked","is_active":false,"sex":"Female"},
{"name":"Lurline Weldrick","school_name":"modular","is_active":true,"sex":"Male"},
{"name":"Meriel Harkes","school_name":"Sharable","is_active":false,"sex":"Female"},
{"name":"Delores Reeders","school_name":"background","is_active":true,"sex":"Male"},
{"name":"Bebe Rosenfield","school_name":"Programmable","is_active":false,"sex":"Female"},
{"name":"Drugi Rolfe","school_name":"client-driven","is_active":false,"sex":"Female"},
{"name":"Dede Wastie","school_name":"infrastructure","is_active":false,"sex":"Female"},
{"name":"Kaycee Jumont","school_name":"extranet","is_active":true,"sex":"Male"},
{"name":"Aurthur Maskell","school_name":"Function-based","is_active":false,"sex":"Female"},
{"name":"Hollie Mayworth","school_name":"Vision-oriented","is_active":true,"sex":"Female"},
{"name":"Conn Charopen","school_name":"contingency","is_active":false,"sex":"Male"},
{"name":"Liane Shallcroff","school_name":"Customizable","is_active":false,"sex":"Male"},
{"name":"Cy Bonanno","school_name":"Future-proofed","is_active":false,"sex":"Female"},
{"name":"Lannie Starten","school_name":"secured line","is_active":true,"sex":"Female"},
{"name":"Shina Cubbin","school_name":"groupware","is_active":true,"sex":"Male"},
{"name":"Kikelia Garforth","school_name":"background","is_active":true,"sex":"Female"},
{"name":"Ricky Dengate","school_name":"disintermediate","is_active":false,"sex":"Female"},
{"name":"Omero Iglesiaz","school_name":"Implemented","is_active":false,"sex":"Female"},
{"name":"Evie Bidgood","school_name":"Versatile","is_active":true,"sex":"Female"},
{"name":"Mead Heap","school_name":"Up-sized","is_active":true,"sex":"Male"},
{"name":"Electra Gilbert","school_name":"moratorium","is_active":false,"sex":"Female"},
{"name":"Cindra Tolputt","school_name":"groupware","is_active":true,"sex":"Female"},
{"name":"Allx Draisey","school_name":"disintermediate","is_active":false,"sex":"Female"},
{"name":"Amy Cottage","school_name":"Reactive","is_active":false,"sex":"Male"},
{"name":"Giralda Halahan","school_name":"Cloned","is_active":false,"sex":"Male"},
{"name":"Mariann Hellewell","school_name":"homogeneous","is_active":false,"sex":"Male"},
{"name":"Dur Dadds","school_name":"client-driven","is_active":false,"sex":"Male"},
{"name":"Kira Bermingham","school_name":"Extended","is_active":true,"sex":"Female"},
{"name":"Cam Villaret","school_name":"Persistent","is_active":true,"sex":"Female"},
{"name":"Jeanelle Lagden","school_name":"homogeneous","is_active":true,"sex":"Male"},
{"name":"Zelig De Caville","school_name":"Ameliorated","is_active":false,"sex":"Male"},
{"name":"Yancey McCurtin","school_name":"actuating","is_active":true,"sex":"Male"},
{"name":"Ros Lemery","school_name":"optimizing","is_active":true,"sex":"Male"},
{"name":"Armando Muncaster","school_name":"Intuitive","is_active":true,"sex":"Male"},
{"name":"April Sheere","school_name":"didactic","is_active":true,"sex":"Male"},
{"name":"Armand Gludor","school_name":"orchestration","is_active":false,"sex":"Female"},
{"name":"Angelia Cirlos","school_name":"Proactive","is_active":false,"sex":"Female"},
{"name":"Brigida Watterson","school_name":"Object-based","is_active":false,"sex":"Male"},
{"name":"Sawyere Sertin","school_name":"User-centric","is_active":true,"sex":"Male"},
{"name":"Dominique Ghilks","school_name":"fresh-thinking","is_active":false,"sex":"Female"},
{"name":"Artemis Bywaters","school_name":"infrastructure","is_active":false,"sex":"Male"},
{"name":"Kristopher Petronis","school_name":"emulation","is_active":true,"sex":"Male"},
{"name":"Herbie Riteley","school_name":"architecture","is_active":false,"sex":"Female"},
{"name":"Jess Dimitrov","school_name":"needs-based","is_active":false,"sex":"Female"},
{"name":"Agnola Jahnig","school_name":"Inverse","is_active":false,"sex":"Female"},
{"name":"Sanders Deerness","school_name":"multimedia","is_active":true,"sex":"Female"},
{"name":"Perla Prewer","school_name":"5th generation","is_active":true,"sex":"Female"},
{"name":"Karissa Cartwright","school_name":"Customer-focused","is_active":false,"sex":"Male"},
{"name":"Caryl Goodspeed","school_name":"Fundamental","is_active":false,"sex":"Male"},
{"name":"Michel Oldaker","school_name":"holistic","is_active":false,"sex":"Female"},
{"name":"Shana Harvatt","school_name":"Operative","is_active":false,"sex":"Female"},
{"name":"Thomas Trayling","school_name":"monitoring","is_active":true,"sex":"Female"},
{"name":"Katleen Houldcroft","school_name":"eco-centric","is_active":false,"sex":"Male"},
{"name":"Twyla Braxton","school_name":"tertiary","is_active":false,"sex":"Male"},
{"name":"Edlin Goater","school_name":"hybrid","is_active":true,"sex":"Female"},
{"name":"Corly Pero","school_name":"static","is_active":false,"sex":"Female"},
{"name":"Aurthur Lincoln","school_name":"Intuitive","is_active":true,"sex":"Male"},
{"name":"Claudia Yegorkov","school_name":"info-mediaries","is_active":false,"sex":"Female"}]

export default siblingData; 